name: Labeling

on:
  issues:
    types: [opened]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/actions/labeling.js`)
            await script(github, context, core)