name: PR Merged

on:
  pull_request:
    types: [closed]

jobs:
  start:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g pnpm
      - run: pnpm i
      - name: 'Update README index'
        run: pnpm readme
      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          message: 'chore: update index'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
